media:
  input: public
  output: /
content:
  - name: blog
    label: Blog
    type: collection
    path: 'src/pages/blog'
    exclude: [ 'index.astro' ]
    view:
      fields: [ title, published, date ]
    fields:
      - name: layout
        type: string
        hidden: true
        default: '../../layouts/Standard.astro'
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: published
        label: Published
        type: boolean
        default: true
      - name: body
        label: Body
        type: rich-text
  - name: community
    label: Community
    type: collection
    path: 'src/pages/measurement-community'
    view:
      fields: [ title, published, date ]
    fields:
      - name: layout
        type: string
        hidden: true
        default: '../../layouts/Standard.astro'
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: published
        label: Published
        type: boolean
        default: true
      - name: body
        label: Body
        type: rich-text
  - name: method
    label: Methodology
    type: file
    path: 'src/pages/methodology.md'
    fields:
      - name: layout
        type: string
        hidden: true
        default: '../layouts/Standard.astro'
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text